version: '3'

services:
  cv:
    image: registry.yosemitesam.ch:443/cv
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.docker.network=traefik-public
        - traefik.enable=true
          #- traefik.port=8080
        - traefik.http.services.cv-cv.loadbalancer.server.port=80
        - traefik.http.routers.cv.rule=Host(`cv.yosemitesam.ch`)
        - traefik.http.routers.cv.entrypoints=https
        - traefik.http.routers.cv.tls.certresolver=le
        - traefik.http.routers.cv.tls=true

networks:
  traefik-public:
    external: true
